# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Crossle
tagline:          'Crossle Song'
description:      'Android and iOS programer, work on <a href="https://shou.tv" target="_blank">Shou.TV</a>'
url:              http://songxiaoming.com
baseurl:          /

author:
  name:           'Crossle Song'
  url:            https://twitter.com/songxiaoming

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/crossle
